<?php
/**
 * Created by PhpStorm.
 * User: Администратор
 * Date: 17.01.2018
 * Time: 0:10
 */

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;

class PhoneBookSearch extends Model
{

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function search($data)
    {
        return new ActiveDataProvider([
            'query' => PhoneBook::find(),
        ]);
    }
}